server:
  servlet:
    context-path: /api/v1
  port: ${PORT:8080}

spring:
  datasource:
    generate-unique-name: false
    name: kameleoon_test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
